import type { Reel } from "@/lib/types";
import { CATEGORIES, DIFFICULTIES } from "@/lib/types";

/* ---------------------------------------------------------------------------
   Reels imported from the ingest pipeline.

   `data/generated/catalog.json` is produced by `npm run import:catalog` from the
   ingest agent's output and committed, so the deployment ships ~200 real reels
   of metadata without the 943MB of video that produced it.

   The file is validated rather than trusted: it is generated by a script that
   calls a language model, and a malformed category or an invented difficulty
   would propagate silently into ranking. Anything that fails validation is
   dropped with a warning instead of poisoning the index.
--------------------------------------------------------------------------- */

interface CatalogFile {
  generatedAt?: string;
  count?: number;
  enrichmentModel?: string | null;
  reels?: unknown[];
}

let file: CatalogFile = {};
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  file = require("./generated/catalog.json") as CatalogFile;
} catch {
  // No import has been run — the hand-authored seed corpus stands alone.
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function validate(raw: unknown): Reel | null {
  if (!isRecord(raw)) return null;

  const id = typeof raw.id === "string" ? raw.id : null;
  const title = typeof raw.title === "string" ? raw.title.trim() : "";
  if (!id || title.length < 2) return null;

  const category = CATEGORIES.includes(raw.category as (typeof CATEGORIES)[number])
    ? (raw.category as Reel["category"])
    : "Other";
  const difficulty = DIFFICULTIES.includes(raw.difficulty as (typeof DIFFICULTIES)[number])
    ? (raw.difficulty as Reel["difficulty"])
    : "Beginner";

  const creator = isRecord(raw.creator) ? raw.creator : {};
  const media = isRecord(raw.media) ? raw.media : {};
  const poster = isRecord(media.poster) ? media.poster : {};
  const stats = isRecord(raw.stats) ? raw.stats : {};

  const substance = typeof raw.substance === "number" ? Math.max(0, Math.min(1, raw.substance)) : 0.2;
  const lane = raw.lane === "both" || raw.lane === "catalog" ? (raw.lane as Reel["lane"]) : "feed";

  return {
    id,
    title,
    creator: {
      handle: typeof creator.handle === "string" ? creator.handle : "@unknown",
      name: typeof creator.name === "string" ? creator.name : "Unknown",
      hue: typeof creator.hue === "number" ? creator.hue : 24,
      verified: creator.verified === true,
    },
    durationSec:
      typeof raw.durationSec === "number" && raw.durationSec > 0 ? Math.round(raw.durationSec) : 30,
    caption: typeof raw.caption === "string" ? raw.caption : "",
    transcript: typeof raw.transcript === "string" ? raw.transcript : "",
    hashtags: Array.isArray(raw.hashtags) ? raw.hashtags.filter((h): h is string => typeof h === "string") : [],
    category,
    topics: Array.isArray(raw.topics) ? raw.topics.filter((t): t is string => typeof t === "string") : [],
    difficulty,
    lane,
    genre: (typeof raw.genre === "string" ? raw.genre : "coding") as Reel["genre"],
    substance,
    hypeMarkers: Array.isArray(raw.hypeMarkers)
      ? raw.hypeMarkers.filter((m): m is string => typeof m === "string")
      : [],
    outcome: typeof raw.outcome === "string" ? raw.outcome : "",
    prerequisites: Array.isArray(raw.prerequisites)
      ? raw.prerequisites.filter((p): p is string => typeof p === "string")
      : [],
    media: {
      poster: {
        from: typeof poster.from === "number" ? poster.from : 24,
        to: typeof poster.to === "number" ? poster.to : 64,
        angle: typeof poster.angle === "number" ? poster.angle : 140,
      },
      ...(typeof media.storageKey === "string" ? { storageKey: media.storageKey } : {}),
      ...(typeof media.localFile === "string" ? { localFile: media.localFile } : {}),
      ...(typeof media.hlsUrl === "string" ? { hlsUrl: media.hlsUrl } : {}),
    },
    stats: {
      likes: typeof stats.likes === "number" ? stats.likes : 0,
      saves: typeof stats.saves === "number" ? stats.saves : 0,
      plays: typeof stats.plays === "number" ? stats.plays : 0,
    },
    publishedAt: typeof raw.publishedAt === "string" ? raw.publishedAt : new Date().toISOString(),
    ...(isRecord(raw.source)
      ? {
          source: {
            platform: String(raw.source.platform ?? "unknown"),
            url: typeof raw.source.url === "string" ? raw.source.url : null,
            owner: typeof raw.source.owner === "string" ? raw.source.owner : null,
            attribution: String(raw.source.attribution ?? ""),
            width: typeof raw.source.width === "number" ? raw.source.width : null,
            height: typeof raw.source.height === "number" ? raw.source.height : null,
            codec: typeof raw.source.codec === "string" ? raw.source.codec : null,
            niches: Array.isArray(raw.source.niches)
              ? raw.source.niches.filter((n): n is string => typeof n === "string")
              : [],
            languages: Array.isArray(raw.source.languages)
              ? raw.source.languages.filter((l): l is string => typeof l === "string")
              : [],
          },
        }
      : {}),
    imported: true,
    enriched: raw.enriched === true,
  };
}

const parsed = (file.reels ?? []).map(validate);
const dropped = parsed.filter((r) => r === null).length;
if (dropped > 0) {
  console.warn(`[catalog] dropped ${dropped} imported reels that failed validation`);
}

export const IMPORTED_REELS: Reel[] = parsed.filter((r): r is Reel => r !== null);

export const IMPORT_INFO = {
  generatedAt: file.generatedAt ?? null,
  enrichmentModel: file.enrichmentModel ?? null,
  total: IMPORTED_REELS.length,
  recommendable: IMPORTED_REELS.filter((r) => r.lane !== "feed").length,
  withMedia: IMPORTED_REELS.filter((r) => r.media.storageKey || r.media.localFile).length,
};
